package io.github.sumirenokai.vesqen.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable

private val DarkColorScheme = darkColorScheme(
    primary = SignalMossBright,
    onPrimary = InkDark,
    primaryContainer = SignalMossDeep,
    onPrimaryContainer = InkLight,
    inversePrimary = SignalMossDeep,
    secondary = MutedDark,
    onSecondary = InkDark,
    secondaryContainer = DarkSecondaryContainer,
    onSecondaryContainer = InkLight,
    tertiary = MutedDark,
    onTertiary = InkDark,
    tertiaryContainer = DarkSecondaryContainer,
    onTertiaryContainer = InkLight,
    background = CarbonBlack,
    onBackground = InkLight,
    surface = CarbonBlack,
    onSurface = InkLight,
    surfaceVariant = CarbonElevated,
    onSurfaceVariant = MutedDark,
    surfaceTint = SignalMossBright,
    inverseSurface = FrostSurface,
    inverseOnSurface = InkDark,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkErrorContainer,
    onErrorContainer = DarkOnErrorContainer,
    outline = DarkOutline,
    outlineVariant = DarkOutlineVariant,
    scrim = CarbonBlack,
    surfaceBright = CarbonBright,
    surfaceContainer = CarbonSurface,
    surfaceContainerHigh = CarbonHigh,
    surfaceContainerHighest = CarbonElevated,
    surfaceContainerLow = CarbonLow,
    surfaceContainerLowest = CarbonLowest,
    surfaceDim = CarbonBlack,
    primaryFixed = SignalMossFixed,
    primaryFixedDim = SignalMossFixedDim,
    onPrimaryFixed = OnSignalMossFixed,
    onPrimaryFixedVariant = OnSignalMossFixedVariant,
    secondaryFixed = InkLight,
    secondaryFixedDim = MutedDark,
    onSecondaryFixed = InkDark,
    onSecondaryFixedVariant = InkDark,
    tertiaryFixed = InkLight,
    tertiaryFixedDim = MutedDark,
    onTertiaryFixed = InkDark,
    onTertiaryFixedVariant = InkDark,
)

private val LightColorScheme = lightColorScheme(
    primary = SignalMossDeep,
    onPrimary = PureWhite,
    primaryContainer = SignalMossBright,
    onPrimaryContainer = InkDark,
    inversePrimary = SignalMossBright,
    secondary = MutedLight,
    onSecondary = PureWhite,
    secondaryContainer = InkLight,
    onSecondaryContainer = InkDark,
    tertiary = MutedLight,
    onTertiary = PureWhite,
    tertiaryContainer = FrostHigh,
    onTertiaryContainer = InkDark,
    background = PureWhite,
    onBackground = InkDark,
    surface = PureWhite,
    onSurface = InkDark,
    surfaceVariant = FrostSurface,
    onSurfaceVariant = MutedLight,
    surfaceTint = SignalMossDeep,
    inverseSurface = InverseDarkSurface,
    inverseOnSurface = InkLight,
    error = VesqenError,
    onError = PureWhite,
    errorContainer = LightErrorContainer,
    onErrorContainer = LightOnErrorContainer,
    outline = LightOutline,
    outlineVariant = MutedDark,
    scrim = CarbonBlack,
    surfaceBright = PureWhite,
    surfaceContainer = FrostContainer,
    surfaceContainerHigh = FrostHigh,
    surfaceContainerHighest = FrostHighest,
    surfaceContainerLow = FrostLow,
    surfaceContainerLowest = FrostLowest,
    surfaceDim = FrostDim,
    primaryFixed = SignalMossFixed,
    primaryFixedDim = SignalMossFixedDim,
    onPrimaryFixed = OnSignalMossFixed,
    onPrimaryFixedVariant = OnSignalMossFixedVariant,
    secondaryFixed = InkLight,
    secondaryFixedDim = MutedDark,
    onSecondaryFixed = InkDark,
    onSecondaryFixedVariant = InkDark,
    tertiaryFixed = InkLight,
    tertiaryFixedDim = MutedDark,
    onTertiaryFixed = InkDark,
    onTertiaryFixedVariant = InkDark,
)

@Composable
fun VesqenTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val colorScheme = if (darkTheme) DarkColorScheme else LightColorScheme

    MaterialTheme(
        colorScheme = colorScheme,
        typography = VesqenTypography,
        content = content,
    )
}
