import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createTestHarness} from 'wrangler';
import {ping} from './fixtures.js';
import {readFileSync} from 'node:fs';
const sampleText=readFileSync(new URL('../../../contracts/device-report/sample-report.json',import.meta.url),'utf8');

test('real local Worker and D1 apply migrations accept reports and roll back quota failures', {timeout:30000}, async t=>{
  const server=createTestHarness({workers:[{configPath:'wrangler.jsonc'}]});
  t.after(()=>server.close());
  await server.listen();
  const worker=server.getWorker();
  await worker.applyD1Migrations('DB');
  const env=await worker.getEnv();
  const post=body=>({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
  const usage=await worker.fetch('/v1/usage',post(ping()));
  assert.equal(usage.status,200,await usage.text());
  assert.equal((await env.DB.prepare('SELECT requests FROM daily_totals').first()).requests,1);
  const accepted=await worker.fetch('/v1/reports',{method:'POST',headers:{'content-type':'application/json'},body:sampleText});
  assert.equal(accepted.status,201,await accepted.text());
  assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM reports').first()).n,1);
  assert.equal((await env.DB.prepare('SELECT document FROM reports').first()).document,sampleText);
  const invalid=JSON.parse(sampleText);
  delete invalid.chainEvidence;
  assert.equal((await worker.fetch('/v1/reports',post(invalid))).status,400);
  assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM reports').first()).n,1);
  await env.DB.prepare('UPDATE daily_totals SET requests=10000').run();
  assert.equal((await worker.fetch('/v1/usage',post(ping()))).status,429);
  assert.equal((await env.DB.prepare('SELECT SUM(count) AS n FROM daily_dimensions').first()).n,7);
  await env.DB.prepare('UPDATE reports SET expires_at=0').run();
  await worker.scheduled({cron:'0 * * * *'});
  assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM reports').first()).n,0);
});
